<?php
// module/Album/view/album/album/delete.phtml:

$title = 'Supprimer un utilisateur';
$url   = $this->url('album', ['action' => 'delete', 'id' => $id]);

$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>

<p>
    Etes vous sur de vouloir supprimer l'utilisateur :
    <?= $this->escapeHtml($album->nom) ?> 
    <?= $this->escapeHtml($album->prenom) ?>?
</p>

<form action="<?= $url ?>" method="post">
<div class="form-group">
    <input type="hidden" name="id" value="<?= (int) $album->id ?>" />
    <input type="submit" class="btn btn-danger" name="del" value="Oui" />
    <input type="submit" class="btn btn-success" name="del" value="Non" />
</div>
</form>